#!/usr/bin/env bash
# Prepare web servers

pip3 uninstall Fabric
sudo apt-get install libffi-dev
sudo apt-get install libssl-dev
sudo apt-get install build-essential
sudo apt-get install python3.4-dev
sudo apt-get install libpython3-dev
pip3 install pyparsing
pip3 install appdirs
pip3 install setuptools
pip3 install cryptography
pip3 install bcrypt
pip3 install PyNaCl
pip3 install Fabric3
